import{a as b,S as L,i as a}from"./assets/vendor-f1a8ff1a.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function n(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerpolicy&&(s.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?s.credentials="include":t.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=n(t);fetch(t.href,s)}})();const v="https://pixabay.com/api/",S="29304756-51da1fab5abbfa991ea2eaa1b";async function m(o,r,n){const i=new URLSearchParams({key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:n});return await b.get(`${v}?${i}`)}function f(o){const r=document.querySelector(".gallery"),n=o.map(({webformatURL:i,tags:t,likes:s,views:l,comments:p,downloads:y,largeImageURL:g})=>`<div class="photo-card">
                <a href = "${g}">
                <img src="${i}" alt="${t}" loading="lazy" />
                </a>
                <div class="info">
                    <p class="info-item"><b>Likes:</b>${s}</p>
                    <p class="info-item"><b>Views:</b>${l}</p>
                    <p class="info-item"><b>Comments:</b>${p}</p>
                    <p class="info-item"><b>Downloads:</b>${y}</p>
                </div> 
            </div>`).join("");r.insertAdjacentHTML("beforeend",n)}const e={searchForm:document.querySelector("#search-form"),gallery:document.querySelector(".gallery"),imageGallery:document.querySelector("photo-card"),submitBtn:document.querySelector(".submit-btn"),loadMoreBtn:document.querySelector(".load-more"),loader:document.querySelector(".loader")};let c=1;const u=40;let d="";const h=new L(".gallery a");e.submitBtn.disabled=!0;e.loader.classList.add("hidden");e.searchForm.addEventListener("submit",B);e.searchForm.addEventListener("input",o=>o.target.value?e.submitBtn.disabled=!1:e.submitBtn.disabled=!0);e.loadMoreBtn.addEventListener("click",M);async function B(o){if(o.preventDefault(),c=1,d=o.currentTarget.searchQuery.value.trim(),e.loader.classList.add("hidden"),e.loadMoreBtn.classList.add("hidden"),d===""){a.error({title:"Error",message:"Sorry, you didn't write what to look for",position:"center"}),e.searchForm.reset(),e.submitBtn.disabled=!0;return}if(e.gallery.innerHTML="",/\d/.test(d))return a.error({title:"Error",message:"Sorry, you can only use letters to search",position:"center"});try{e.loader.classList.remove("hidden");const{data:r}=await m(d,c,u);r.totalHits===0?(e.loader.classList.add("hidden"),a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again.",position:"center"})):(e.loader.classList.add("hidden"),f(r.hits),h.refresh(),a.info({title:"Information",message:`Hooray! We found ${r.totalHits} images.`,position:"center"}),r.totalHits>u&&e.loadMoreBtn.classList.remove("hidden"),r.totalHits<=u&&(e.loadMoreBtn.classList.add("hidden"),a.info({title:"Information",message:"We're sorry, but you've reached the end of search results.",position:"center"})))}catch(r){console.error(r),e.loadMoreBtn.classList.add("hidden"),e.loader.classList.add("hidden"),a.error({title:"Server error",message:"Oops! Something went wrong! Try reloading the page!",position:"center"})}}async function M(){c+=1;try{e.loader.classList.remove("hidden");const{data:o}=await m(d,c,u);e.loader.classList.add("hidden"),f(o.hits),h.refresh();const r=Math.ceil(o.totalHits/u);if(c<r)e.loadMoreBtn.classList.remove("hidden");else{e.loadMoreBtn.classList.add("hidden"),a.info({title:"Information",message:"We're sorry, but you've reached the end of search results.",position:"center"});return}}catch(o){console.log(o)}}
//# sourceMappingURL=commonHelpers.js.map
