import{a as b,i as l,S as L}from"./assets/vendor-f1a8ff1a.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerpolicy&&(a.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?a.credentials="include":e.crossorigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function s(e){if(e.ep)return;e.ep=!0;const a=n(e);fetch(e.href,a)}})();const S="https://pixabay.com/api/",v="29304756-51da1fab5abbfa991ea2eaa1b";async function m(r,t,n){const s=new URLSearchParams({key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:n});return await b.get(`${S}?${s}`)}function f(r){const t=document.querySelector(".gallery"),n=r.map(({webformatURL:s,tags:e,likes:a,views:i,comments:y,downloads:h,largeImageURL:g})=>`<div class="photo-card">
                <a href = "${g}">
                <img src="${s}" alt="${e}" loading="lazy" />
                <div class="info">
                    <p class="info-item"><b>Likes:</b>${a}</p>
                    <p class="info-item"><b>Views:</b>${i}</p>
                    <p class="info-item"><b>Comments:</b>${y}</p>
                    <p class="info-item"><b>Downloads:</b>${h}</p>
                </div> 
                </a>
            </div>`).join("");t.insertAdjacentHTML("beforeend",n)}const o={searchForm:document.querySelector("#search-form"),gallery:document.querySelector(".gallery"),imageGallery:document.querySelector("photo-card"),submitBtn:document.querySelector(".submit-btn"),loadMoreBtn:document.querySelector(".load-more"),loader:document.querySelector(".loader")};let c=1;const u=40;let d="";o.submitBtn.disabled=!0;o.loader.classList.add("hidden");o.searchForm.addEventListener("submit",q);o.searchForm.addEventListener("input",r=>r.target.value?o.submitBtn.disabled=!1:o.submitBtn.disabled=!0);o.loadMoreBtn.addEventListener("click",w);async function q(r){if(r.preventDefault(),c=1,d=r.currentTarget.searchQuery.value.trim(),o.gallery.innerHTML="",/\d/.test(d))return l.error({title:"Error",message:"Sorry, you can only use letters to search",position:"center"});try{const{data:t}=await m(d,c,u);o.loader.classList.remove("hidden"),t.totalHits===0?(o.loader.classList.add("hidden"),l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again.",position:"center"})):(o.loader.classList.add("hidden"),f(t.hits),p(),l.info({title:"Information",message:`Hooray! We found ${t.totalHits} images.`,position:"center"}),t.totalHits>u&&o.loadMoreBtn.classList.remove("hidden"))}catch(t){console.error(t),o.loader.classList.add("hidden"),l.error({title:"Server error",message:"Oops! Something went wrong! Try reloading the page!",position:"center"})}}async function w(){c+=1;try{const{data:r}=await m(d,c,u);f(r.hits),p();const t=Math.ceil(r.totalHits/u);if(c<t)o.loadMoreBtn.classList.remove("hidden");else{l.info({title:"Information",message:"We're sorry, but you've reached the end of search results.",position:"center"});return}}catch(r){console.log(r)}}function p(){new L(".gallery a").refresh()}
//# sourceMappingURL=commonHelpers.js.map
