import{a as p,i as l,S as g}from"./assets/vendor-f1a8ff1a.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const y="https://pixabay.com/api/",h="29304756-51da1fab5abbfa991ea2eaa1b";async function b(o,r,i){const n=new URLSearchParams({key:h,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:i});return await p.get(`${y}?${n}`)}function S(o){const r=document.querySelector(".gallery"),i=o.map(({webformatURL:n,tags:e,likes:t,views:a,comments:m,downloads:f,largeImageURL:d})=>`
            <div class="photo-card">
                <a href = "${d}">
                <img src="${n}" alt="${e}" loading="lazy" />
                <div class="info">
                    <p class="info-item"><b>Likes:</b>${t}</p>
                    <p class="info-item"><b>Views:</b>${a}</p>
                    <p class="info-item"><b>Comments:</b>${m}</p>
                    <p class="info-item"><b>Downloads:</b>${f}</p>
                </div> 
                </a>
            </div>`).join("");r.insertAdjacentHTML("beforeend",i)}const s={searchForm:document.querySelector("#search-form"),gallery:document.querySelector(".gallery"),imageGallery:document.querySelector("photo-card"),submitBtn:document.querySelector(".submit-btn")};let c="",u=1;const L=40;s.submitBtn.disabled=!0;s.searchForm.addEventListener("submit",v);s.searchForm.addEventListener("input",o=>o.target.value?s.submitBtn.disabled=!1:s.submitBtn.disabled=!0);function v(o){if(o.preventDefault(),u=1,c=o.currentTarget.searchQuery.value.trim(),s.gallery.innerHTML="",/\d/.test(c))return l.error({title:"Error",message:"Sorry, you can only use letters to search",position:"center"});b(c,u,L).then(({data:r})=>{r.totalHits===0?l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again.",position:"center"}):(S(r.hits),$(),l.info({title:"Information",message:`Hooray! We found ${r.totalHits} images.`,position:"center"}))}).catch(r=>{console.error(r),l.error({title:"Server error",message:"Oops! Something went wrong! Try reloading the page!",position:"center"})})}function $(){new g(".gallery a").refresh()}
//# sourceMappingURL=commonHelpers.js.map
